# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BuClubApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'SwiftSoup'
  use_frameworks!

  pod 'GoogleAPIClientForREST/Gmail', '~> 1.2.1'
  pod 'GoogleSignIn', '~> 5.0'
  
  # Pods for BuClubApp
end
